# Intro to Numpy - Thomas Pellet

In [5]:
import numpy as np
# Create a 1-D array by passing a list into NumPy's array() function.
np.array([8, 4, 6, 0, 2])

# The string representation has no commas or an array() label.
print(np.array([1, 3, 5, 7, 9]))


[1 3 5 7 9]


In [10]:
A = np.array( [ [1, 2, 3],[4, 5, 6] ] )
print(A[1,0])

4


In [15]:
#Problem 1

A = np.array( [ [3, -1, 4],[1, 5, -9] ] )
B = np.array( [ [2,6,-5,3],[5,-8,9,7], [9,-3,-2,-3]] )
AB = A @ B

print(AB)

[[ 37  14 -32 -10]
 [-54  -7  58  65]]


In [30]:
# Problem 2

A = np.array([[3,1,4],[1,5,9],[-5,3,1]])
print(-(A@A@A) + 9*A@A - 15*A)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [39]:
# Problem 3
A = np.triu(np.ones(7))
B = np.tril(-1*np.ones(7)) + np.triu(np.full(7,5)) - 5*np.diag(np.ones(7))

ABA = A@B@A
ABA = ABA.astype(np.float64)

print(ABA)



[[ -7.  -8.  -3.   8.  25.  48.  77.]
 [ -6. -12. -12.  -6.   6.  24.  48.]
 [ -5. -10. -15. -14.  -7.   6.  25.]
 [ -4.  -8. -12. -16. -14.  -6.   8.]
 [ -3.  -6.  -9. -12. -15. -12.  -3.]
 [ -2.  -4.  -6.  -8. -10. -12.  -8.]
 [ -1.  -2.  -3.  -4.  -5.  -6.  -7.]]


In [103]:
# Problem set 4
A = np.diag(-1*np.ones(5))
print(A)
def negativetozero(A):
    copy = np.copy(A)
    mask = copy < 0
    copy[mask] = 0
    print(copy)
negativetozero(A)

5
[[-1.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0. -1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [140]:
# Problem set 5
def stack():
    A = np.arange(6).reshape(3,-1).T
    B = 3*np.tril(np.ones(3))
    C = -2*np.eye(3)
    print(C.shape)
    zeros = np.zeros((3,3))
    firstcol = np.vstack((zeros,A,B))
    print(firstcol.shape)
    secondcol = np.vstack((A.T,np.zeros((A.shape[0] + B.shape[0],A.T.shape[1]))))
    print(secondcol.shape)
    print(np.full_like(A,0))
    print(np.zeros((A.shape[0],C.shape[1])))
    eye = np.eye(3)
    zero = np.zeros((A.shape[0],C.shape[1]))
    thirdcol = np.vstack((eye,zero,C))
    print(thirdcol.shape)
    result = np.hstack((firstcol, secondcol, thirdcol))
    print(result)          
stack()

(3, 3)
(8, 3)
(8, 2)
[[0 0 0]
 [0 0 0]]
[[0. 0. 0.]
 [0. 0. 0.]]
(8, 3)
[[ 0.  0.  0.  0.  1.  1.  0.  0.]
 [ 0.  0.  0.  2.  3.  0.  1.  0.]
 [ 0.  0.  0.  4.  5.  0.  0.  1.]
 [ 0.  2.  4.  0.  0.  0.  0.  0.]
 [ 1.  3.  5.  0.  0.  0.  0.  0.]
 [ 3.  0.  0.  0.  0. -2. -0. -0.]
 [ 3.  3.  0.  0.  0. -0. -2. -0.]
 [ 3.  3.  3.  0.  0. -0. -0. -2.]]


In [148]:
# Problem 6
A = np.arange(20).reshape(5,-1)
print(A)
def rowstoch(A):
    sumrow = A.sum(axis = 1).reshape((-1,1))
    print(sumrow)
    A = A / sumrow
    print(A)
rowstoch(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 6]
 [22]
 [38]
 [54]
 [70]]
[[0.         0.16666667 0.33333333 0.5       ]
 [0.18181818 0.22727273 0.27272727 0.31818182]
 [0.21052632 0.23684211 0.26315789 0.28947368]
 [0.22222222 0.24074074 0.25925926 0.27777778]
 [0.22857143 0.24285714 0.25714286 0.27142857]]


In [180]:
# Problem 7

grid = np.load("grid-Copy1.npy")
print(grid)
def greatestproduct(grid):
    # horizontal
    hor = np.max(grid[:,:-3] * grid[:,1:-2] * grid[:,2:-1] * grid[:,3:])
    # vertical
    vert = np.max(grid[:-3,:] * grid[1:-2,:] * grid[2:-1,:] * grid[3:,:])
    #rightdiag
    rightdiag = np.max(grid[:-3,:-3] * grid[1:-2,1:-2] * grid[2:-1,2:-1] * grid[3:,3:])
    #leftdiag
    leftdiag = np.max(grid[:-3,3:] * grid[1:-2,2:-1] * grid[2:-1,1:-2] * grid[3:,:-3])
    winner = max(hor,vert,leftdiag,rightdiag)
    print(winner)
greatestproduct(grid)

[[ 8  2 22 97 38 15  0 40  0 75  4  5  7 78 52 12 50 77 91  8]
 [49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48  4 56 62  0]
 [81 49 31 73 55 79 14 29 93 71 40 67 53 88 30  3 49 13 36 65]
 [52 70 95 23  4 60 11 42 69 24 68 56  1 32 56 71 37  2 36 91]
 [22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80]
 [24 47 32 60 99  3 45  2 44 75 33 53 78 36 84 20 35 17 12 50]
 [32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70]
 [67 26 20 68  2 62 12 20 95 63 94 39 63  8 40 91 66 49 94 21]
 [24 55 58  5 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72]
 [21 36 23  9 75  0 76 44 20 45 35 14  0 61 33 97 34 31 33 95]
 [78 17 53 28 22 75 31 67 15 94  3 80  4 62 16 14  9 53 56 92]
 [16 39  5 42 96 35 31 47 55 58 88 24  0 17 54 24 36 29 85 57]
 [86 56  0 48 35 71 89  7  5 44 44 37 44 60 21 58 51 54 17 58]
 [19 80 81 68  5 94 47 69 28 73 92 13 86 52 17 77  4 89 55 40]
 [ 4 52  8 83 97 35 99 16  7 97 57 32 16 26 26 79 33 27 98 66]
 [88 36 68 87 57 62 20 72  3 46 33 67 46 55 12 32 63 93